### ISSUE TITLE
Use general Scala code conventions

### ISSUE THREAD

**Issue by mfirry** [unicredit/sbt-swagger-codegen#12]
Let's try and use general code convention for autogenerated code.

For example models `case class`es should be [camelCase style with the very first letter of the name capitalized](http://docs.scala-lang.org/style/naming-conventions.html#classestraits).

**Comment by andreaTP** [comment]
In this case name are not formatted by the tool but just taken from the
yaml.
This can easily be respected by multiple languages implementations.

**Comment by mfirry** [comment]
You can get in trouble anyway... Say my yaml contains something like:

``` yaml
definitions:
  case:
    required:
      - id
      - subject
```

or

``` yaml
definitions:
  class:
    required:
      - room
      - teacher
```

You could probably generate something like 

``` scala
case class `case`(...
```

But still...
