### ISSUE TITLE
Print warning for produce section not supported

### ISSUE THREAD

**Issue by gianluca-sabena** [unicredit/sbt-swagger-codegen#7]
If the yaml produce section contain a content type not supported, display a warning

This swagger yaml 

```
paths:
  /pets:
    get:
      description: Returns all pets from the system that the user has access to
      operationId: findPets
      produces:
        - application/json
        - application/xml
        - text/xml
        - text/html
```

Must display 3 warnings, sine only application/json is now supported
