### ISSUE TITLE
When have a GET parameter with boolean, value is not casted.

### ISSUE THREAD

**Issue by RyoNishikawa** [unicredit/sbt-swagger-codegen#78]
When define request parameter with type boolean in yaml, parsed value type mismatch controler argument type.

For example...

```yaml
  /example/path:
    get:
      summary: 'example text'
      operationId: 'getExample'
      produces:
        - 'application/json'
      parameters:
        - name: 'flag'
          in: 'query'
          description: 'Flag of boolean'
          required: false
          type: 'boolean'
          default: true
```

Compile the code, and then following message prints out.

```
[error] ExampleRouter.scala:XX:XX: type mismatch;
[error]  found   : Option[String]
[error]  required: Option[Boolean]
[error]       controller.getExample(detail)
```

Sorry for my poor English...
